DSE.App/Controllers/ArchiveController.cs
using DSE.DataAccess.Data;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Configuration;
using System.Web.Mvc;

namespace DSE.App.Controllers
{
    public class ArchiveController : Controller
    {
        static string dseCnnString = WebConfigurationManager.ConnectionStrings["dseCnnString"].ConnectionString;
        ArchiveFactory _archiveFactory = new ArchiveFactory(dseCnnString);

        // GET: Archive
        public ActionResult Index()
        {
            ViewBag.hideSidebar = true;
            var archives = _archiveFactory.GetArchives();
            return View(archives);
        }
    }
}

DSE.App/Controllers/HomeController.cs
using DSE.App.Models;
using DSE.Common;
using DSE.DataAccess.Data;
using log4net;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Text;
using System.Web.Configuration;
using System.Web.Mvc;

namespace DSE.App.Controllers
{
    public class HomeController : Controller
    {
        const int FUNCTION_ID = 1;
        static string dseCnnString = WebConfigurationManager.ConnectionStrings["dseCnnString"].ConnectionString;
        KPIFactory _kpiFactory = new KPIFactory(dseCnnString);
        KPIDateFactory _kpiDateFactory = new KPIDateFactory(dseCnnString);
        KpiDataTypeFactory _kpiDataTypesFactory = new KpiDataTypeFactory(dseCnnString);
        ILog log = log4net.LogManager.GetLogger(typeof(HomeController));

        private bool CheckLogin()
        {
            if (Session[DSEConstant.LoginState] == null
                || Convert.ToBoolean(Session[DSEConstant.LoginState]) == false)
            {
                return false;
            }
            return true;
        }

        public ActionResult Index(string archiveName)
        {
            if (CheckLogin())
            {
                ViewBag.UserName = Session[DSEConstant.UserName].ToString();
                ViewBag.hideSidebar = true;
                ViewBag.showFields = _kpiFactory.GetKPIShowFields()?.config_value;
                ViewBag.archiveName = archiveName?.Trim();
                var fieldsName = _kpiFactory.GetFieldsName();
                var fieldsType = _kpiDataTypesFactory.GetKpiDataTypes();
                ViewBag.fieldsName = fieldsName;
                ViewBag.fieldsType = fieldsType;
                var dates = _kpiDateFactory.GetKPIDate(archiveName);
                if(dates != null)
                {
                    ViewBag.startDate = dates.Item1;
                    ViewBag.endDate = dates.Item2;
                }

                return View();
            }
            else
            {
                return RedirectToAction("Login", "User");
            }
        }

        public ContentResult GetDataTable(DataTableRequest querry, string id)
        {
            int count = 0;
            var data = _kpiFactory.GetKPIs(id, querry.start, querry.length, ref count);

            var categoriesDto = new DataTableResult<object>(querry.draw, count, count, data);
            var result = JsonConvert.SerializeObject(categoriesDto);

            return Content(result, "application/json");
        }

        public ActionResult Detail(string id, string archiveName)
        {
            if (!CheckLogin()) return RedirectToAction("Login", "User");
            try
            {
                var kpi = _kpiFactory.GetKPIById(id);
                ViewBag.kpi = kpi;
                ViewBag.archiveName = archiveName;
            }
            catch (Exception ex)
            {
                log.Error("Load detail KPI " + archiveName, ex);
                return RedirectToAction("Index");
            }

            return View();
        }

        [HttpPost]
        public ActionResult Update(object kpi, string archiveName)
        {
            if (!CheckLogin()) return RedirectToAction("Login", "User");

            var _param = HttpContext.Request.Params;
            var allTypes = new Dictionary<string, Type>();
            var allKeys = _kpiFactory.GetFieldsName(allTypes);
            string sqlCommand = "UPDATE [vw_target_kpi] SET {0} WHERE [o_target_kpi_id] = @id";

            StringBuilder sqlParams = new StringBuilder("");
            foreach (var field in allKeys)
            {
                if (_param.AllKeys.Contains(field) && FieldEditable(field))
                {
                    sqlParams.Append($"{field} = @{field},");
                }

            }

            // remove last ',' character
            sqlParams.Remove(sqlParams.Length - 1, 1);

            sqlCommand = string.Format(sqlCommand, sqlParams);

            try
            {
                using (SqlConnection con = new SqlConnection(dseCnnString))
                {
                    con.Open();
                    using (SqlCommand cmd = new SqlCommand(sqlCommand, con))
                    {

                        foreach (var field in allKeys)
                        {
                            if (_param.AllKeys.Contains(field) && FieldEditable(field))
                            {
                                if (allTypes[field] == typeof(Decimal))
                                {
                                    if (string.IsNullOrEmpty(_param[field]))
                                    {
                                        cmd.Parameters.Add($"@{field}", SqlDbType.Decimal).Value = DBNull.Value;
                                    }
                                    else
                                    {
                                        Decimal value = 0;
                                        if (Decimal.TryParse(_param[field], out value))
                                        {
                                            cmd.Parameters.Add($"@{field}", SqlDbType.Decimal).Value = value;
                                        }
                                        continue;
                                    }
                                }

                                if (allTypes[field] == typeof(String))
                                {
                                    cmd.Parameters.Add($"@{field}", SqlDbType.NChar).Value = _param[field];
                                    continue;
                                }
                                if (allTypes[field] == typeof(Int32))
                                {
                                    cmd.Parameters.Add($"@{field}", SqlDbType.Int).Value = _param[field];
                                    continue;
                                }
                                if (allTypes[field] == typeof(DateTime))
                                {
                                    cmd.Parameters.Add($"@{field}", SqlDbType.DateTime).Value = _param[field];
                                }
                            }
                        }

                        cmd.Parameters.Add("@id", SqlDbType.NChar).Value = _param["o_target_kpi_id"];

                        var result = cmd.ExecuteNonQuery();
                    }
                }

            }
            catch (System.Exception ex)
            {
                log.Error("Update KPI " + archiveName, ex);
            }
            return RedirectToAction("Index", new { archiveName = archiveName });
        }

        public bool FieldEditable(string fieldName)
        {
            bool editable = fieldName.Contains("_tab");
            return editable;
        }

        public ActionResult UpdateKPIShowFields(string fields)
        {
            if (!CheckLogin()) return RedirectToAction("Login", "User");
            try
            {
                _kpiFactory.UpdateKPIShowFields(fields);

            }
            catch (Exception ex)
            {
                log.Error("Update home KPI column ", ex);

            }
            return RedirectToAction("Index");
        }
    }
}

DSE.App/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>
<div class="main-content container-fluid">
    <p>Use this area to provide additional information.</p>
    </div>

DSE.App/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

DSE.App/Views/Home/Detail.cshtml
@{
    ViewBag.Title = "Detail";
}
<div class="page-head">
    <ol class="breadcrumb">
        <li><a href="/">Home</a></li>
        <li class="active"><a href="#"> Detail KPI </a></li>
    </ol>
    <div>
        <p style="margin: 0">Lastupdate: <span id="last-update"></span></p> 
    </div>
</div>
<div class="main-content container-fluid">
    <div class="panel panel-default kpi-update">
        
        <form class="tab-container"  method="post" , action="@Url.Action("Update","Home", new { archiveName = ViewBag.archiveName})">
            <ul class="nav nav-tabs">
                <li class="active"><a href="#info" data-toggle="tab">Site Information</a></li>
                <li><a href="#attendance" data-toggle="tab">Attendance</a></li>
                <li><a href="#projects" data-toggle="tab">Projects</a></li>
            </ul>
            <div class="tab-content">
                <div id="info" class="tab-pane active cont">
                    <div id="formkpi_tab1" class="form-horizontal group-border-dashed">
                        <div class="form-group">
                            <label class="col-sm-3 control-label"></label>
                            <div class="col-sm-6 xs-pt-5 text-right">
                                <input type="submit" value="Update" class="btn btn-success" />
                            </div>
                        </div>
                    </div>
                </div>
                <div id="attendance" class="tab-pane cont">
                    <div id="formkpi_tab2" class="form-horizontal group-border-dashed">
                        <div class="form-group">
                            <label class="col-sm-3 control-label"></label>
                            <div class="col-sm-6 xs-pt-5 text-right">
                                <input type="submit" value="Update" class="btn btn-success" />
                            </div>
                        </div>
                    </div>                </div>
                <div id="projects" class="tab-pane">
                    <div id="formkpi_tab3" class="form-horizontal group-border-dashed">
                        <div class="form-group">
                            <label class="col-sm-3 control-label"></label>
                            <div class="col-sm-6 xs-pt-5 text-right">
                                <input type="submit" value="Update" class="btn btn-success" />
                            </div>
                        </div>
                    </div>         
                </div>
            </div>
        </form>
    </div>
</div>

@section scripts {
    <script>
        let kpi = @Html.Raw(Json.Encode(ViewBag.kpi));
        for(i in kpi){
            if(!(i.indexOf("_tab") > 0 || i == "o_target_kpi_id")){
                continue;
            }
            let value = kpi[i];
            let label = i.replace("_tab1", "")
                .replace("_tab2", "")
                .replace("_tab3", "")
                .replace(/_/g, " ");
            if(value == null || value == "null"){
                value = "";
            }

            let formGroup = `
                    <div class="form-group ${i == "o_target_kpi_id" ? "hide" : ""}">
                      <label class="col-sm-3 control-label">${label}</label>
                      <div class="col-sm-6 xs-pt-5">
                        <input type="text" value="${value}" id="${i}" name="${i}" class="form-control input-xs" ${i == "o_target_kpi_id" ? "readonly" : ""}>
                      </div>
                    </div>
                `;
            if(i.indexOf("_tab1") > 0 || i == "o_target_kpi_id"){
                $("#formkpi_tab1").append(formGroup);
            }

            if(i.indexOf("_tab2") > 0){
                $("#formkpi_tab2").append(formGroup);
            }

            if(i.indexOf("_tab3") > 0){
                $("#formkpi_tab3").append(formGroup);
            }
            
        }

        let bottomButton = `

                    <div class="form-group">
                        <label class="col-sm-3 control-label"></label>
                        <div class="col-sm-6 xs-pt-5 text-right">
                            <input type="submit" value="Update" class="btn btn-success"/>
                        </div>
                    </div>
                    `;
        $("#formkpi_tab1").append(bottomButton);
        $("#formkpi_tab2").append(bottomButton);
        $("#formkpi_tab3").append(bottomButton);
        $('#last-update').append(moment(kpi["modification_date"]).format("MMM DD, YYYY hh:mm:ss A"));
    </script>

}

DSE.App/Views/Home/Index.cshtml
@{
    ViewBag.Title = "";
    List<string>
    fieldsName = ViewBag.fieldsName;
    ViewBag.Collap = true;

    string startDate = ViewBag.startDate != null ? ((DateTime)ViewBag.startDate).ToString("MMM dd, yyyy") : "";
    string endDate = ViewBag.endDate != null ? ((DateTime)ViewBag.endDate).ToString("MMM dd, yyyy") : "";

    string dateRange = ViewBag.startDate != null && ViewBag.endDate != null ? $"<b>From:</b> {startDate} <b>to:</b> {endDate}" : "";
    }

    <div class="main-content container-fluid main-kpi">
        <div class="row">
            <div class="col-sm-12">
                <div class="panel panel-default ">
                    <div class="panel-heading panel-heading-divider">
                        KPI @ViewBag.archiveName
                        <span class="panel-subtitle">@Html.Raw(dateRange) </span>
                        <a class="mdi mdi-settings btn" style="float: right" onclick="openModal()"></a>
                        <a href="@Url.Action(" Index","Archive")" class="mdi mdi-folder btn" style="float: right"></a>
                        <span class="panel-subtitle"></span>
                    </div>
                    <div class="panel-body">
                        <table title="Double click to edit row" class="table table-striped table-hover table-fw-widget" id="logtable"></table>
                    </div>
                </div>
            </div>
        </div>
        <div id="mod-update-fiels" tabindex="-1" role="dialog" class="modal fade" style="display: none;">
            <div class="modal-dialog modal-lg">
                <div class="modal-content" style="max-width: 900px">
                    <div class="modal-header">
                        <button type="button" data-dismiss="modal" aria-hidden="true" class="close"><span class="mdi mdi-close"></span></button>
                        <h3>Show fields</h3>
                    </div>
                    <div class="modal-body">
                        <div id="config-modal">
                        </div>
                    </div>
                    <div class="modal-footer">
                        <a href="javascript:updateConfig()" class="btn btn-primary modal-close">Update</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    @section css {
    <link href="~/Content/lib/datatables/css/dataTables.bootstrap.min.css" rel="stylesheet" />
    <style>
        #logtable tr {
            cursor: pointer;
        }
    </style>
    }
    @section scripts{
    <script src="~/Content/lib/datatables/js/jquery.dataTables.js"></script>
    <script src="~/Content/lib/datatables/js/dataTables.bootstrap.js"></script>

    <script>
        let fields = @Html.Raw(Json.Encode(fieldsName));
        // fields.sort();
        let fieldsType = @Html.Raw(Json.Encode(ViewBag.fieldsType));
        // fieldsType.sort();
        let valueFields = fields.filter((field, index) => {
            return field.indexOf("_tab") > 0 || (field == "o_target_kpi_id")
        })

        let showFieldsString = "@ViewBag.showFields";
        let showFields = showFieldsString.split(",");

        function getDataType(fieldName) {
            let field = fieldsType.find((f, index) => {
                return f.ColumnName == fieldName
            })

            return field && field.DataType;
        }

        //console.log("showFields")
        //console.log(showFields)
        //console.log("fields")
        //console.log(fields)
        //console.log("valueFields")
        //console.log(valueFields)

        let columns = [];
        for (let i in valueFields) {
            let item = fields[i];
            let dataType = getDataType(item);
            columns.push({
                title: item.replace("_tab1", "").replace("_tab2","").replace("_tab3","").replace(/_/g, " "),
                data: function(data){
                    if(data[item] == null || data[item] =="null"){
                        data[item] = "";
                    }

                    let content = data[item];
                    if(isNaN(content)){
                        return content;
                    }
                    else {
                        let number
                        switch (dataType) {
                            case 'money':
                                number = new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD' }).format(content);//"$ " + content.toFixed(3).replace(/(\d)(?=(\d{3})+\.)/g, '$1,');
                                break;
                            case 'decimal':
                                number = new Intl.NumberFormat('en-US', { style: 'decimal', minimumFractionDigits: 2 }).format(content)
                                break;
                            default:
                                number = new Intl.NumberFormat('en-US', { style: 'decimal' }).format(content)
                                break;

                        }
                        return number
                    }
                    return content;
                },
                defaultContent: "",
                visible: showFields.includes(item),
                className: 'int, money, decimal, float'.includes(dataType) ? 'text-right' : ''
            })
        }

        $(document).ready(function () {
            logTable = $('#logtable').DataTable({
                'select': {
                    'style': 'multi',
                    'selector': 'td:not(:first-child)'
                },
                "autoWidth": false,
                "ordering": true,
                "processing": true,
                "serverSide": true,
                "pageLength": 10,
                "searching": false,
                'columns': columns,
                "scrollX": true,
                'ajax': {
                    type: "POST",
                    contentType: "application/json",
                    url: '@Url.Action("GetDataTable", "Home", new { id = ViewBag.archiveName })',
                    data: function (d) {
                        return JSON.stringify(d);
                    }
                },
            })

            $('#logtable tbody').on('click', 'tr', function () {
                var data = logTable.row( this ).data();
                location.href="@Url.Action("detail", "home", new { id = "replaceId", archiveName = ViewBag.archiveName })".replace("replaceId", data["o_target_kpi_id"]);
            } );

            AddCongif();
        });

        function AddCongif(){
            let configCheckbox = [];
            for(let i in valueFields){
                let fieldName = valueFields[i];
                let displayName = fieldName.replace("_tab1", "").replace("_tab2","").replace("_tab3","").replace(/_/g, " ");
                let checked = showFields.includes(fieldName) ? " checked" : "";
                let html = `
                    <div class="col-md-6">
                        <div class="be-checkbox">
                          <input id="chk-${fieldName}" type="checkbox" onChange="checkField('${fieldName}')"${checked}>
                          <label for="chk-${fieldName}">${displayName}</label>
                        </div>
                    </div>
                    `;
                $("#config-modal").append(html);
            }
        }

        function checkField(fieldName){
            console.log(fieldName);
            let checked = $("#chk-" + fieldName).is(":checked");

            if(checked) {
                if(!showFields.includes(fieldName)){
                    showFields.push(fieldName);
                }
            }
            else {
                if(showFields.includes(fieldName)){
                    showFields.splice(showFields.indexOf(fieldName), 1)
                }
            }
        }

        function updateConfig() {
            let configString = "";
            for(let i in showFields){
                let fieldName = showFields[i];

                if( i == showFields.length - 1) {
                    configString += fieldName;
                }
                else {
                    configString += fieldName + ","
                }
            }

            location.href = '@Url.Action("UpdateKPIShowFields", "Home")' + "?fields=" + configString;
        }

        function closeModal() {
            $('#mod-update-fiels').modal('hide')
        }

        function openModal() {
            $('#mod-update-fiels').modal('show')
        }

    </script>
    }