DSE.App/Controllers/DESLogController.cs
using DSE.App.Models;
using DSE.DataAccess.Data;
using DSE.DataAccess.Models;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Configuration;
using System.Web.Mvc;

namespace DSE.App.Controllers
{
    public class DESLogController : Controller
    {
        const int FUNCTION_ID = 1;
        static string dseCnnString = WebConfigurationManager.ConnectionStrings["dseCnnString"].ConnectionString;
        LogViewFactory _clientFactory = new LogViewFactory(dseCnnString);
        SourceFactory _sourceFactory = new SourceFactory(dseCnnString);

        // GET: DESLog
        public ActionResult Index(Guid id, int type)
        {
            ViewBag.source = _sourceFactory.GetSource(id);
            ViewBag.id = id.ToString();
            return View();
        }

        public ContentResult GetDataTable(DataTableRequest querry, Guid id)
        {
            int count = 0;
            var data = _clientFactory.GetLogs(id, querry.start, querry.length, ref count);

            var categoriesDto = new DataTableResult<LogViewModel>(querry.draw, count, count, data);
            var result = JsonConvert.SerializeObject(categoriesDto);

            return Content(result, "application/json");
        }

        public ActionResult Detail(Guid id, Guid source)
        {
            ViewBag.source = _sourceFactory.GetSource(source);
            ViewBag.id = id.ToString();
            var model = _clientFactory.LogDetailByJobId(id);
            return View("DetailList", model);
        }
    }
}

DSE.App/Views/DESLog/Detail.cshtml
@model DSE.DataAccess.Models.LogDetailViewModel

@{
    ViewBag.Title = "Log";
}
<div class="page-head">
    <ol class="breadcrumb page-head-nav">
        <li><a href="@Url.Action("Index")">Logs</a></li>
        <li class="active">Log Detail</li>
    </ol>
</div>
<div class="main-content container-fluid">
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.job_name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.job_name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.step_name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.step_name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.run_status)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.run_status)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.run_duration)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.run_duration)
        </dd>

    </dl>
</div>

DSE.App/Views/DESLog/DetailList.cshtml
@using DSE.DataAccess.Models
@model IEnumerable<DSE.DataAccess.Models.LogDetailViewModel>

@{
    ViewBag.Title = "Log detail";
    Source source = ViewBag.source;
}

<div class="page-head">
    <ol class="breadcrumb">
        <li><a href="@Url.Action("Index","DESLog", new { id = source.SourceId, type = 0})">@source.SourceName Logs</a></li>
        <li class="active"><a href=""title="@ViewBag.id">Detail</a></li>
    </ol>
</div>
<div class="main-content container-fluid"><div class="row">
    <div class="col-sm-12">
        <div class="panel panel-default ">
            <div class="panel-heading panel-heading-divider hide">Log detail<span class="panel-subtitle hide">@ViewBag.id</span></div>
            <div class="panel-body">
                <table class="table table-striped table-hover table-fw-widget">
                    <tr>
                        <th>
                            @Html.DisplayNameFor(model => model.job_name)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.step_name)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.run_status)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.run_duration)
                        </th>
                    </tr>

                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.job_name)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.step_name)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.run_status)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.run_duration)
                            </td>
                        </tr>
                    }

                </table>
            </div>
        </div>
    </div>
</div>
    
</div>

DSE.App/Views/DESLog/Index.cshtml
@using DSE.DataAccess.Models
@model DSE.DataAccess.Models.LogViewModel

@{
    ViewBag.Title = "Logs";
    Source source = ViewBag.source;
}

<div class="page-head">
    <ol class="breadcrumb">
        @*<li><a href="@Url.Action("Index","Home")">Home</a></li>*@
        <li class="active"><a href="#">@source.SourceName / Logs</a></li>
    </ol>
</div>
<div class="main-content container-fluid">
    <div class="row">
        <div class="col-sm-12">
            <div class="panel panel-default ">
                @*<div class="panel-heading panel-heading-divider">Action logs<span class="panel-subtitle"> @source.SourceName </span></div>*@
                <div class="panel-body">
                    <table class="table table-striped table-hover table-fw-widget" id="logtable"></table>
                </div>
            </div>
        </div>
    </div>
</div>



@section css {
    <link href="~/Content/lib/datatables/css/dataTables.bootstrap.min.css" rel="stylesheet" />
}
@section scripts{
    <script src="~/Content/lib/datatables/js/jquery.dataTables.min.js"></script>
    <script src="~/Content/lib/datatables/js/dataTables.bootstrap.min.js"></script>

    <script>
        $.extend(true, $.fn.dataTable.defaults, {
            dom:
            "<'row be-datatable-header'<'col-sm-6'l><'col-sm-6'f>>" +
            "<'row be-datatable-body'<'col-sm-12'tr>>" +
            "<'row be-datatable-footer'<'col-sm-5'i><'col-sm-7'p>>"
        });

        var columns = [
            {
                // o_job_id
                title: '@Html.DisplayNameFor(model => model.o_job_id)',
                mData: "o_job_id",
                visible: false,
                defaultContent: ""
            }, {
                // ActionTime
                title: '@Html.DisplayNameFor(model => model.job_name)',
                mData: "job_name",
                defaultContent: ""
            }, {
                // run_status
                title: '@Html.DisplayNameFor(model => model.run_status)',
                target: 1,
                mData: "run_status",
                defaultContent: ""
            }, {
                // run_date
                title: '@Html.DisplayNameFor(model => model.run_date)',
                target: 2,
                data: function (data) {
                    //return data.run_date.substring(0, 10);
                    return moment(data.run_date).format('MMM DD, YYYY')
                },
                defaultContent: ""
            }, {
                // run_time
                title: '@Html.DisplayNameFor(model => model.run_time)',
                target: 3,
                data: function (data) {
                    //return data.run_time.substring(0, 8);
                    return moment(data.run_date.substring(0, 10) + 'T' + data.run_time).format('hh:mm:ss A')
                },
                defaultContent: "",
            }, {
                // run_duration
                title: '@Html.DisplayNameFor(model => model.run_duration)',
                target: 4,
                mData: "run_duration",
                defaultContent: "",
            }
            , {
                // user_name
                title: '@Html.DisplayNameFor(model => model.user_name)',
                target: 5,
                mData: "user_name",
                defaultContent: "",
            }, {
                // Detail
                title: '',
                target: 6,
                data: function (data) {
                    let tag = `<a class="btn btn-default" href='@Url.Action("Detail", "DESLog", new { id = "replaceId", source = source.SourceId })'>Detail</a>`.replace("replaceId", data.o_job_id);
                    return tag
                },
                defaultContent: ""
            }
        ];

        var logTable = logTable || {}
        var a = window.dataTablesLang
        $(document).ready(function () {
            logTable = $('#logtable').DataTable({
                'select': {
                    'style': 'multi',
                    'selector': 'td:not(:first-child)'
                },
                "autoWidth": false,
                "ordering": false,
                "processing": true,
                "serverSide": true,
                "pageLength": 10,
                "searching": false,
                'columns': columns,
                'ajax': {
                    type: "POST",
                    contentType: "application/json",
                    url: '@Url.Action("GetDataTable", "DESLog", new { id = ViewBag.id })',
                    data: function (d) {
                        return JSON.stringify(d);
                    }
                },
            })
        });
    </script>
}