DSE.App/Controllers/CommonAPIController.cs
using DSE.Common;
using DSE.DataAccess.Data;
using log4net;
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Configuration;
using System.Web.Http;

namespace DSE.App.Controllers
{
    public class CommonAPIController : ApiController
    {
        static string dseCnnString = WebConfigurationManager.ConnectionStrings["dseCnnString"].ConnectionString;
        SourceFactory _sourceFactory = new SourceFactory(dseCnnString);
        ILog log = log4net.LogManager.GetLogger(typeof(CommonAPIController));

        [AcceptVerbs("GET", "HEAD")]
        public bool CheckConnection(string connection) {

            //if (Session[DSEConstant.LoginState] == null
            //    || Convert.ToBoolean(Session[DSEConstant.LoginState]) == false)
            //{
            //    return false;
            //}

            bool res = false;

            try
            {
                using (SqlConnection conn = new SqlConnection(connection))
                {
                    conn.Open(); // throws if invalid
                    res = true;
                }
            }
            catch (Exception ex)
            {
                log.Error("Check connection "+connection+" false", ex);
                return false;
            }
            return res;
        }
    }
}

DSE.App/Controllers/SourceController.cs
using DSE.App.Models;
using DSE.Common;
using DSE.Common.Excel;
using DSE.DataAccess;
using DSE.DataAccess.Data;
using DSE.DataAccess.Models;
using log4net;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.IO;
using System.Web.Configuration;
using System.Web.Mvc;

namespace DSE.App.Controllers
{
    public class SourceController : Controller
    {
        static string dseCnnString = WebConfigurationManager.ConnectionStrings["dseCnnString"].ConnectionString;
        UserFactory _userFactory = new UserFactory(dseCnnString);
        RoleFactory _roleFactory = new RoleFactory(dseCnnString);
        ClientFactory _clientFactory = new ClientFactory(dseCnnString);
        SourceFactory _sourceFactory = new SourceFactory(dseCnnString);
        SourceMappingFactory _sourceMappingFactory = new SourceMappingFactory(dseCnnString);
        ILog log = log4net.LogManager.GetLogger(typeof(SourceController));

        private bool CheckLogin()
        {
            if (Session[DSEConstant.LoginState] == null
                || Convert.ToBoolean(Session[DSEConstant.LoginState]) == false)
            {
                return false;
            }
            return true;
        }

        public ActionResult Index()
        {
            if (!CheckLogin()) return RedirectToAction("Login", "User");

            try
            {
                List<Source> sourceCollection = _sourceFactory.GetSourceCollection();
                return View(sourceCollection);
            }
            catch (Exception ex)
            {
                log.Error("Get source list", ex);
                return RedirectToAction("Index", "Home");
            }
        }

        public ActionResult TargetIndex()
        {
            if (!CheckLogin()) return RedirectToAction("Login", "User");

            try
            {
                List<Source> sourceCollection = _sourceFactory.GetSourceCollection();
                return View(sourceCollection);
            }
            catch (Exception ex)
            {
                log.Error("Get source list", ex);
                return RedirectToAction("Index", "Home");
            }
        }

        public ActionResult Config(Guid id, int type)
        {
            if (!CheckLogin()) return RedirectToAction("Login", "User");
            switch (type)
            {
                case (int)SourceType.SqlServer:
                    return RedirectToAction("SQLConfig", "Source", new { id = id });
                case (int)SourceType.Excel:
                    return RedirectToAction("ExcelConfig", "Source", new { id = id });
                default:
                    return RedirectToAction("Index", "Source");
            }
        }

        public ActionResult ExcelConfig(Guid id)
        {
            if (!CheckLogin()) return RedirectToAction("Login", "User");
            Source source = new Source();
            if (id == null) return RedirectToAction("Index", "Error");
            try
            {
                source = _sourceFactory.GetSource(id);
                if (source != null && !string.IsNullOrEmpty(source.CurrentTableName))
                {
                    try
                    {
                        var tablesname = source.CurrentTableName.Split(',');
                        source.CurrentData = new List<DataTable>();
                        foreach (var item in tablesname)
                        {
                            source.CurrentData.Add(_sourceFactory.GetSourceImportedData(item));
                        }
                    }
                    catch (Exception ex)
                    {
                        log.Error("Can not get temp data of " + source.SourceName, ex);
                        source.CurrentData = null;
                    }
                }
            }
            catch (Exception ex)
            {
                log.Error("Get source", ex);
                return RedirectToAction("Index", "Source");
            }
            return View(source);
        }

        public ActionResult SQLConfig(Guid id)
        {
            if (!CheckLogin()) return RedirectToAction("Login", "User");
            if (id == null) return RedirectToAction("Index", "Error");
            Source source = new Source();
            try
            {
                source = _sourceFactory.GetSource(id);               
            }
            catch (Exception ex)
            {
                log.Error("Get source", ex);
                return RedirectToAction("Index", "Source");
            }
            return View(source);           
        }

        [HttpPost]
        public ActionResult SQLConfig(Source source)
        {
            if (!CheckLogin()) return RedirectToAction("Login", "User");
            ViewBag.SuccessMessage = string.Empty;
            ViewBag.ErrorMessage = string.Empty;
            try
            {
                var sourcex = _sourceFactory.GetSource(source.SourceId);

                sourcex.UpdateBy = Guid.Parse(Session[DSEConstant.UserId].ToString());
                sourcex.UpdateDate = DateTime.Now;
                sourcex.Source_ServerName = source.Source_ServerName;
                sourcex.Source_Server_DatabaseName = source.Source_Server_DatabaseName;
                sourcex.Source_Server_Password = source.Source_Server_Password;
                sourcex.Source_Server_Username = source.Source_Server_Username;
                source = _sourceFactory.Update(sourcex);
                if (source.Updated)
                {
                    ViewBag.SuccessMessage = "SQL Connection setting updated";
                }
            }
            catch (Exception ex)
            {
                log.Error("Save connection setting ", ex);
                ViewBag.ErrorMessage = "Conection setting can not save. Return message : " + ex.Message;
            }

            return View(source);

           
        }

        [HttpPost]
        public ActionResult ExcelConfig(Source source)
        {
            if (!CheckLogin()) return RedirectToAction("Login", "User");
            Guid userId = (Guid)Session[DSEConstant.UserId];
            try
            {
                string tablenames = "";
                string messTablenames = "";
                var fileName = string.Empty;
                int res = 0;
                
                // File validate
                if (Request.Files.Count > 0 )
                {
                    string script = "" + Environment.NewLine;
                    string scriptIns = "" + Environment.NewLine;
                    var file = Request.Files[0];


                    if (file != null && file.ContentLength > 0 && (file.FileName.EndsWith(".xls") || file.FileName.EndsWith(".xlsx")))
                    {
                        fileName = Path.GetFileName(file.FileName);
                        Directory.CreateDirectory(Server.MapPath("~/Temp/"));
                        var pathTemp = Path.Combine(Server.MapPath("~/Temp/"), fileName);
                        file.SaveAs(pathTemp);

                        ExcelHelper eh = new ExcelHelper();
                        script += eh.CreateTableScript(pathTemp);
                        scriptIns += eh.CreateInsertScript(pathTemp);
                        Directory.CreateDirectory(Server.MapPath("~/Backup/"));
                        var path = Path.Combine(Server.MapPath("~/Backup/"), DateTime.Now.ToString("ddmmyyyyhhmmss_") + fileName);
                        file.SaveAs(path);

                        var paths = eh.GetSheets(pathTemp);
                        if (paths.Count > 0)
                        {
                            foreach (var tableName in paths)
                            {
                                tablenames += "temp_" + Path.GetFileNameWithoutExtension(file.FileName) + "_" + tableName + ",";
                                messTablenames += Path.GetFileNameWithoutExtension(file.FileName) + "_" + tableName + ",";
                            }
                            int endIdx = tablenames.Length;
                            tablenames = tablenames.Substring(0, endIdx - 1);
                            int endIdxx = messTablenames.Length;
                            messTablenames = messTablenames.Substring(0, endIdxx - 1); 
                        }

                        if (System.IO.File.Exists(pathTemp)) System.IO.File.Delete(pathTemp);

                        // Run create table with transaction
                        script += Environment.NewLine + "";
                        SqlHelper.ExecuteNonQuery(dseCnnString, CommandType.Text, script);
                        res = SqlHelper.ExecuteNonQuery(dseCnnString, CommandType.Text, scriptIns);

                        ViewBag.SuccessMessage = "";
                        if (res > 0)
                        {

                           
                            source.UpdateBy = userId;
                            source.UpdateDate = DateTime.Now;
                            source.CurrentTableName = tablenames;
                            source.UploadFileName = fileName;
                            source.NumberOfRecord = res;                            
                            source = _sourceFactory.Update(source);

                            // Validation
                            DataTable resTable = _sourceFactory.GetValidationTable(source.SourceId, userId);

                            if (resTable != null && resTable.Rows.Count > 0)
                            {
                                ViewBag.ErrorMessage = fileName + " file import unsuccessfully, please check validation result. ";
                                source.Status = false;
                                source.UpdateBy = userId;
                                                              
                                source.LastRun = DateTime.Now;

DSE.App/Views/Source/Excel.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Excel</title>
</head>
<body>
    <div> 
    </div>
</body>
</html>

DSE.App/Views/Source/ExcelConfig.cshtml
@model DSE.DataAccess.Models.Source
@using DSE.App.Helpers
@using System.Data;
@{
    ViewBag.Title = "Data Sources";
}
<div class="page-head">
    <ol class="breadcrumb">
        <li><a href="@Url.Action("Index","Source")">Data Sources</a></li>
        <li><a href="#">@Model.SourceName </a></li>
        <li class="active"><a href="#"> Import File </a></li>
    </ol>
</div>
<div class="main-content container-fluid">
    <div class="row">
        @using (Html.BeginForm("ExcelConfig", "Source", FormMethod.Post, new { enctype = "multipart/form-data", @class = "form-horizontal group-border-dashed" }))
        {
        <!--Responsive table-->
            <div class="col-sm-12">
                <div class="panel panel-default ">
                    @*<div class="panel-heading panel-heading-divider">Import Excel <span class="panel-subtitle">Upload source file to validate & import</span></div>*@
                    <div class="panel-body">
                        @Html.AntiForgeryToken()
                        @Html.HiddenFor(model => model.SourceId)
                        @Html.HiddenFor(model => model.ClientId)
                        @Html.HiddenFor(model => model.CreateBy)
                        @Html.HiddenFor(model => model.UpdateBy)
                        @Html.HiddenFor(model => model.SourceType)
                        @Html.HiddenFor(model => model.Source_ServerName)
                        @Html.HiddenFor(model => model.Source_Server_Username)
                        @Html.HiddenFor(model => model.Source_Server_Password)
                        @Html.HiddenFor(model => model.Source_Server_Salt)
                        @Html.HiddenFor(model => model.Source_Server_Port)
                        @Html.HiddenFor(model => model.Source_Server_DatabaseName)
                        @Html.HiddenFor(model => model.Is_Scheduled)
                        @Html.HiddenFor(model => model.Schedule_Start_Time)
                        @Html.HiddenFor(model => model.Schedule_Interval)
                        @Html.HiddenFor(model => model.Is_Active)
                        @Html.HiddenFor(model => model.UpdateDate)
                        @Html.HiddenFor(model => model.CreateDate)
                        @Html.HiddenFor(model => model.Source_Server_FilePath)
                        <div class="form-group hide">
                            @Html.LabelFor(model => model.SourceName, htmlAttributes: new { @class = "control-label col-md-3" })
                            <div class="col-sm-6">
                                @Html.EditorFor(model => model.SourceName, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                                @Html.MyValidationMessageFor(model => model.SourceName)
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-3 control-label">Upload an excel File</label>
                            <div class="col-sm-6">
                                <input type="file" name="file" id="file" data-multiple-caption="{count} files selected" class="inputfile">
                                <label for="file" class="btn-default"> <i class="mdi mdi-upload"></i><span>Browse files...					</span></label>
                                <input type="submit" value="Upload & Import" class="btn btn-primary" />
                            </div>
                        </div>
                        @*<div class="form-group">
                            <div class="col-sm-6 col-md-offset-3">
                                <input type="submit" value="Upload & Import" class="btn btn-primary" />
                            </div>
                        </div>*@
                        @*@if (ViewBag.Edit != null)
                        {
                            if (!ViewData.ModelState.IsValid)
                            {
                                <div role="alert" class="alert alert-danger alert-dismissible">
                                    <button type="button" data-dismiss="alert" aria-label="Close" class="close"><span aria-hidden="true" class="mdi mdi-close"></span></button><span class="icon mdi mdi-close-circle-o"></span><strong>Danger!</strong>@Html.ValidationSummary(true, "", new { @class = "text-danger" })
                                </div>
                            }
                        }*@
                        @if (ViewBag.SuccessMessage != null && ViewBag.SuccessMessage.Length > 0)
                        {
                            <div role="alert" class="alert alert-success alert-icon alert-icon-border alert-dismissible">
                                <div class="icon"><span class="mdi mdi-check"></span></div>
                                <div class="message">
                                    <button type="button" data-dismiss="alert" aria-label="Close" class="close"><span aria-hidden="true" class="mdi mdi-close"></span></button><strong>Good!</strong> @ViewBag.SuccessMessage.
                                </div>
                            </div>
                            @*<div class="form-group">
                                <div class="col-sm-6 col-md-offset-3">
                                    @Html.ActionLink("Go to Mapping", "ExcelMapping", new { id = Model.SourceId }, new { @class = "btn btn-primary" })
                                </div>
                            </div>*@
                        }
                        @if (ViewBag.ErrorMessage != null && ViewBag.ErrorMessage.Length > 0)
                        {
                            <div role="alert" class="alert alert-danger alert-icon alert-icon-border alert-dismissible">
                                <div class="icon"><span class="mdi mdi-check"></span></div>
                                <div class="message">
                                    <button type="button" data-dismiss="alert" aria-label="Close" class="close"><span aria-hidden="true" class="mdi mdi-close"></span></button><strong>No!</strong> @ViewBag.ErrorMessage.
                                </div>
                            </div>                            

                        }
                    </div>
                </div>
            </div>
        }
        <div class="col-sm-12">
            <div class="panel panel-default ">
                @{
                    string updateDate = Model.UpdateDate?.ToString("MMM dd, yyyy hh:mm:ss tt");
                }
                <div class="panel-heading panel-heading-divider">Current Imported Data<span class="panel-subtitle"> Last import time : @updateDate  </span></div>
                <div class="panel-body">
                    @if (Model.CurrentData != null)
                    {
                        foreach (DataTable table in Model.CurrentData)
                        {
                            <div style="width:100%; overflow-x:scroll">
                                <h4>@table.TableName</h4>
                                <table class="table table-condensed table-hover table-bordered table-striped">
                                    <thead>
                                        <tr>
                                            @for (int i = 0; i < table.Columns.Count; i++)
                                            {
                                                <th>@table.Columns[i].ColumnName</th>
                                            }
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @for (int i = 0; i < table.Rows.Count; i++)
                                        {
                                            <tr>
                                                @for (int j = 0; j < table.Columns.Count; j++)
                                                {
                                                    <td>@table.Rows[i][j].ToString()</td>
                                                }
                                            </tr>
                                        }
                                    </tbody>
                                </table>
                            </div>
                        }
                    }
                </div>
            </div>
        </div>
    </div>
</div>
@section scripts{
    <script>
        $(document).ready(function () {
            // File input
            $('.inputfile').each(function () {
                var $input = $(this),
                    $label = $input.next('label'),
                    labelVal = $label.html();

                $input.on('change', function (e) {
                    var fileName = '';

                    if (this.files && this.files.length > 1)
                        fileName = (this.getAttribute('data-multiple-caption') || '').replace('{count}', this.files.length);
                    else if (e.target.value)
                        fileName = e.target.value.split('\\').pop();

                    if (fileName)
                        $label.find('span').html(fileName);
                    else
                        $label.html(labelVal);
                });
            });
        });
    </script>
}

DSE.App/Views/Source/SQLConfig.cshtml
@model DSE.DataAccess.Models.Source
@using DSE.App.Helpers
@using System.Data;

@{
    ViewBag.Title = "Data Sources";
}



<div class="page-head">
    <ol class="breadcrumb">
        <li><a href="@Url.Action("Index","Source")">Data Sources</a></li>
        <li><a href="#">@Model.SourceName </a></li>
        <li class="active"><a href="#"> Connection </a></li>
    </ol>
</div>
<div class="main-content container-fluid">
    <div class="row">
        @using (Html.BeginForm("SQLConfig", "Source", FormMethod.Post, new { enctype = "multipart/form-data", @class = "form-horizontal group-border-dashed" }))
        {
        <!--Responsive table-->
            <div class="col-sm-12">


                <div class="panel panel-default ">
                    <div class="panel-heading panel-heading-divider">SQL Connection Setting <span class="panel-subtitle">Config the connection information of source</span></div>
                    <div class="panel-body">

                        @if (ViewBag.ErrorMessage != null && ViewBag.ErrorMessage.Length > 0)
                        {
                            <div role="alert" class="alert alert-warning alert-icon alert-icon-border alert-dismissible">
                                <div class="icon"><span class="mdi mdi-alert-triangle"></span></div>
                                <div class="message">
                                    <button type="button" data-dismiss="alert" aria-label="Close" class="close"><span aria-hidden="true" class="mdi mdi-close"></span></button><strong>Error!</strong> @ViewBag.ErrorMessage.
                                </div>
                            </div>
                            if (!ViewData.ModelState.IsValid)
                            {
                                <div role="alert" class="alert alert-warning alert-icon alert-icon-border alert-dismissible">
                                    <div class="icon"><span class="mdi mdi-alert-triangle"></span></div>
                                    <div class="message">
                                        <button type="button" data-dismiss="alert" aria-label="Close" class="close"><span aria-hidden="true" class="mdi mdi-close"></span></button><strong>Warning!</strong> @Html.ValidationSummary(true, "")
                                    </div>
                                </div>
                            }
                        }

                        @if (ViewBag.SuccessMessage != null && ViewBag.SuccessMessage.Length > 0)
                        {
                            <div role="alert" class="alert alert-success alert-icon alert-icon-border alert-dismissible">
                                <div class="icon"><span class="mdi mdi-check"></span></div>
                                <div class="message">
                                    <button type="button" data-dismiss="alert" aria-label="Close" class="close"><span aria-hidden="true" class="mdi mdi-close"></span></button><strong>Good!</strong> @ViewBag.SuccessMessage.
                                </div>
                            </div>

                        }


                        @Html.AntiForgeryToken()
                        @Html.HiddenFor(model => model.SourceId)
                        @Html.HiddenFor(model => model.ClientId)
                        @Html.HiddenFor(model => model.CreateBy)
                        @Html.HiddenFor(model => model.UpdateBy)
                        @Html.HiddenFor(model => model.SourceType)
                        @Html.HiddenFor(model => model.Source_Server_Salt)
                        @Html.HiddenFor(model => model.Source_Server_Port)
                        @Html.HiddenFor(model => model.Is_Scheduled)
                        @Html.HiddenFor(model => model.Schedule_Start_Time)
                        @Html.HiddenFor(model => model.Schedule_Interval)
                        @Html.HiddenFor(model => model.Is_Active)
                        @Html.HiddenFor(model => model.UpdateDate)
                        @Html.HiddenFor(model => model.CreateDate)
                        @Html.HiddenFor(model => model.Source_Server_FilePath)


                        <!-- User Name-->
                        <div class="form-group">
                            @Html.LabelFor(model => model.SourceName, htmlAttributes: new { @class = "control-label col-sm-3" })
                            <div class="col-sm-6">
                                @Html.EditorFor(model => model.SourceName, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                                @Html.MyValidationMessageFor(model => model.SourceName)
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-3 control-label">Server Name or IP</label>
                            <div class="col-sm-6">
                                @Html.EditorFor(model => model.Source_ServerName, new { htmlAttributes = new { @class = "form-control " } })
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-3 control-label">Login</label>
                            <div class="col-sm-6">
                                @Html.EditorFor(model => model.Source_Server_Username, new { htmlAttributes = new { @class = "form-control " } })
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-3 control-label">Password</label>
                            <div class="col-sm-6">
                                @Html.EditorFor(model => model.Source_Server_Password, new { htmlAttributes = new { @class = "form-control " , type="password" } })
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-3 control-label">Target Database Name</label>
                            <div class="col-sm-6">
                                @Html.EditorFor(model => model.Source_Server_DatabaseName, new { htmlAttributes = new { @class = "form-control " } })
                            </div>
                        </div>                       
                        <div class="form-group">
                            <div class="col-sm-6 col-md-offset-3">
                                <input type="submit" value="Save" class="btn btn-primary" />
                                <input type="button" id="btn_check_connection" value="Test connection" onclick="checkConnection()" class="btn btn-default" /> 
                                <span style="display:none" id="connectionCheckLoader" class="mdi loader"></span>
                                <span id="connetionStatus" style="display:none; color:forestgreen" class="mdi mdi-check">Connection validated</span>
                                <span id="connetionStatusFalse" style="display:none;color:red" class="mdi mdi-alert-triangle">Failed to connect</span>
                            </div>
                        </div>                       
                       
                        @if (ViewBag.SuccessMessage != null && ViewBag.SuccessMessage.Length > 0)
                        {
                          
                            <div class="form-group">
                                <div class="col-sm-6 col-md-offset-3">
                                    @Html.ActionLink("Go to Mapping", "SQLMapping", new { id = Model.SourceId }, new { @class = "btn btn-primary" })
                                </div>
                            </div>
                        }
                    </div>
                </div>


            </div>
        }
        
    </div>
</div>
@section scripts{

    <script>
        $(document).ready(function () {
            // File input
            $('.inputfile').each(function () {
                var $input = $(this),
                    $label = $input.next('label'),
                    labelVal = $label.html();

                $input.on('change', function (e) {
                    var fileName = '';

                    if (this.files && this.files.length > 1)
                        fileName = (this.getAttribute('data-multiple-caption') || '').replace('{count}', this.files.length);
                    else if (e.target.value)
                        fileName = e.target.value.split('\\').pop();

                    if (fileName)
                        $label.find('span').html(fileName);
                    else
                        $label.html(labelVal);
                });
            });
        });
        function checkConnection() {
            // build connection string
            //Server=myServerAddress;Database=myDataBase;User Id=myUsername; Password = myPassword;
            var cs = "Server=" + $('#Source_ServerName').val() + ";Database=" + $('#Source_Server_DatabaseName').val() + ";User Id=" + $('#Source_Server_Username').val() + ";Password = " + $('#Source_Server_Password').val() + ";";

            // Change buttion state
            $('#btn_check_connection').prop('value', 'Checking...');
            $('#btn_check_connection').prop('disabled', 'disabled');
            $('#connetionStatus').hide();
            $('#connetionStatusFalse').hide();
            $('#connectionCheckLoader').css("display", "inline-block");
           

            // Call API

            var checkAction =  "@Url.Action("CheckConnection","CommonAPI",new {connecion=string.Empty})";

            var jqxhr = $.get("/api/commonapi/checkconnection"+"?connection="+cs, function (data) {
                //alert("success");
                console.log(data);
            })
              .done(function (data) {
                  console.log(data);
                  if (data) {
                      $('#connetionStatusFalse').hide();
                      $('#connetionStatus').css("display","inline-block");
                  } else {
                      $('#connetionStatus').hide();
                      $('#connetionStatusFalse').css("display","inline-block");
                  }
              })
              .fail(function () {
                  console.log("Error");
                  $('#connetionStatus').hide();
                  $('#connetionStatusFalse').css("display", "inline-block");
              })
              .always(function () {
                  
                  $('#btn_check_connection').prop('value', 'Test Connection');
                  $('#btn_check_connection').prop('disabled', '');
                  $('#connectionCheckLoader').css("display", "none");
              });


            // Show result
        }
    </script>

}